FROM node:20 as builder
WORKDIR /app
COPY webui webui
WORKDIR /app/webui
RUN corepack enable
RUN rm -rf .yarn/unplugged && yarn install --immutable --immutable-cache
RUN yarn run build-prod
FROM nginx:stable
COPY --from=builder /app/webui/dist /usr/share/nginx/html
