FROM node:lts AS builder
WORKDIR /app
RUN corepack enable
COPY webui webui
WORKDIR /app/webui
RUN corepack prepare yarn@4.5.0 --activate
RUN yarn run build-prod
FROM nginx:stable
RUN mkdir -p /var/cache/nginx /var/run /var/log/nginx /run \
    && chown -R 1000:1000 /var/cache/nginx /var/run /var/log/nginx /run /etc/nginx/conf.d
USER 1000
COPY --from=builder /app/webui/dist /usr/share/nginx/html
